title: Amulya Kurapati
logo: /assets/img/amulya-portfolio.jpeg
description: Amulya Kurapati
MSc Computer Science | Software Developer | Machine Learning Enthusiast
Passionate about building intelligent applications using Python, Machine Learning, SQL, and Full-Stack Development. This portfolio showcases my projects, technical skills, and work in AI, data analysis, and software development.
show downloads: true
theme: jekyll-theme-minimal
